import * as SQLite from 'expo-sqlite';
const db = SQLite.openDatabaseSync('fitmind.db');
interface OutfitFeedback { action: string; color_score: number; skin_score: number; final_score: number; }
interface AccuracyMetrics { totalPredictions: number; correctPredictions: number; accuracyRate: number; improvementTrend: 'improving' | 'stable' | 'declining'; confidenceCalibration: number; }
interface WeightVector { colorWeight: number; skinWeight: number; tasteWeight: number; geminiWeight: number; patternWeight: number; occasionWeight: number; }
const DEFAULT_WEIGHTS: WeightVector = { colorWeight: 0.2, skinWeight: 0.3, tasteWeight: 0.25, geminiWeight: 0.15, patternWeight: 0.05, occasionWeight: 0.05 };
const DAMPING = 0.15; const clamp = (v:number,min:number,max:number)=>Math.max(min,Math.min(max,v));
export async function updateWeightsFromFeedback(feedback: OutfitFeedback[]): Promise<WeightVector> { if (feedback.length < 5) return DEFAULT_WEIGHTS; const current = await loadWeights(); const recent = feedback.slice(-30); const positives = recent.filter(f => ['worn','liked','fitcheck_loved'].includes(f.action)); const negatives = recent.filter(f => ['rejected','fitcheck_bad'].includes(f.action)); if (!positives.length && !negatives.length) return current; const corr=(g:(f:OutfitFeedback)=>number)=>((positives.reduce((s,f)=>s+g(f),0)/(positives.length||1))-(negatives.reduce((s,f)=>s+g(f),0)/(negatives.length||1)))/10; const newWeights: WeightVector = { colorWeight: clamp(current.colorWeight + corr(f => f.color_score) * DAMPING, 0.1, 0.9), skinWeight: clamp(current.skinWeight + corr(f => f.skin_score) * DAMPING, 0.1, 0.9), tasteWeight: clamp(current.tasteWeight + corr(f => f.final_score - f.skin_score) * DAMPING, 0.1, 0.9), geminiWeight: current.geminiWeight, patternWeight: current.patternWeight, occasionWeight: current.occasionWeight }; const total = Object.values(newWeights).reduce((s,v)=>s+v,0); (Object.keys(newWeights) as Array<keyof WeightVector>).forEach((k)=>{ newWeights[k]=newWeights[k]/total; }); await saveWeights(newWeights); return newWeights; }
async function loadWeights(): Promise<WeightVector> { const row = await db.getFirstAsync<{color_weights: string}>('SELECT color_weights FROM taste_profile WHERE id = "taste"'); if (!row) return DEFAULT_WEIGHTS; try { return { ...DEFAULT_WEIGHTS, ...JSON.parse(row.color_weights || '{}') }; } catch { return DEFAULT_WEIGHTS; } }
async function saveWeights(weights: WeightVector): Promise<void> { await db.runAsync(`UPDATE taste_profile SET color_weights = ?, last_updated = datetime('now') WHERE id = 'taste'`, [JSON.stringify(weights)]); }
export async function calculateAccuracyMetrics(): Promise<AccuracyMetrics> { const recent = await db.getAllAsync<any>(`SELECT * FROM outfit_feedback ORDER BY created_at DESC LIMIT 100`); if (!recent.length) return { totalPredictions: 0, correctPredictions: 0, accuracyRate: 0, improvementTrend: 'stable', confidenceCalibration: 0.5 }; const positive = recent.filter((f:any)=>['worn','liked'].includes(f.action)).length; const early = recent.slice(Math.max(0, recent.length - 20), recent.length - 10); const latest = recent.slice(recent.length - 10); const earlyRate = early.filter((f:any)=>['worn','liked'].includes(f.action)).length / (early.length || 1); const latestRate = latest.filter((f:any)=>['worn','liked'].includes(f.action)).length / (latest.length || 1); return { totalPredictions: recent.length, correctPredictions: positive, accuracyRate: Math.round((positive / recent.length) * 100), improvementTrend: latestRate > earlyRate + 0.05 ? 'improving' : latestRate < earlyRate - 0.05 ? 'declining' : 'stable', confidenceCalibration: latestRate }; }
